apiVersion: v1
kind: Service
metadata:
  name: peviewer
spec:
  type: ClusterIP
  selector:
    app: igwn-peviewer
  ports:
    - name: streamlit
      port: 80
      protocol: TCP
      targetPort: streamlit
