name: Docker Image CI

on:
  push:
    branches: [ dockerize ]
  pull_request:
    branches: [ dockerze ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag pe-viewer:$(date +%s)