name: Docker Image CI

on:
  push:
    branches: [ dockerize ]
  pull_request:
    branches: [ dockerize ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
             TS=$(date +%s)
             docker build . --file docker/Dockerfile --tag gcr.io/${{ github.actor }}/pe-viewer:${TS}
             docker push gcr.io/${{ github.actor }}/pe-viewer:${TS}
